services:
  - docker
language: java
matrix:
  include:
    - jdk: oraclejdk9
      env:
        COVERAGE=0.24
    - jdk: openjdk10
      env:
        COVERAGE=0.24
env:
  global:
    - DOCKER_PASSWORD= 0b4371f2-c74d-4493-aa6b-d9c9a949888b
    - DOCKER_LOGIN= ghemamalini154
script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  .gradlew -p ./monolithic/ui check
  .gradlew -p ./monolithic/service/cart check
  .gradlew -p ./monolithic/service/user check
  .gradlew -p ./monolithic/repository/order check
  .gradlew -p ./monolithic/repository/cart check
  .gradlew -p ./monolithic/repository/product check
  .gradlew -p ./monolithic/repository/user check
  travis encrypt DOCKER_PASSWORD=password --add env.global --com
  bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username\"${DOCKER_LOGIN}\" --password-stdin"
  .gradlew -p ./monolithic/ui packageToContainer
  docker tag zutherb/monolithic-shop:latest $DOCKER_LOGIN/web-doc154_ghe:latest
  docker push $DOCKER_LOGIN/web-doc154_ghe:latest
  chmod +x ./script/deploy.sh
  find . -name jacocoTestReport.csv|xargs cat|awk -F', ' '{print $3" "$4" "$5}'
  
